src/AppBundle/Entity/Invoice.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * Invoice
 *
 * @ORM\Table(name="invoice")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\InvoiceRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Invoice
{
    use TimestampableEntity;

    const STATUS_PENDING = 'Awaiting Payment';
    const STATUS_PAID = 'Paid';
    const STATUS_VOID = 'Void';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var SupplierInvoice
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\SupplierInvoice", inversedBy="invoice")
     * @ORM\JoinColumn(name="supplier_invoice_id", referencedColumnName="id")
     */
    private $supplierInvoice;

    /**
     * @var float
     *
     * @ORM\Column(name="commission_rate", type="decimal", precision=10, scale=4)
     */
    private $commissionRate;

    /**
     * @var float
     *
     * @ORM\Column(name="commission", type="decimal", precision=10, scale=2)
     */
    private $commission;

    /**
     * @var string
     * @ORM\Column(name="tier_level", type="string", length=10)
     */
    private $tierLevel;

    /**
     * @var string
     *
     * @ORM\Column(name="xero_id", type="string", length=255)
     */
    private $xeroId;

    /**
     * @var \DateTime
     * @ORM\Column(name="due_at", type="date")
     */
    private $dueAt;

    /**
     * @var \DateTime
     * @ORM\Column(name="next_invoice_issue_at", type="date")
     */
    private $nextInvoiceIssueAt;

    /**
     * @var Payment[]
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Payment", mappedBy="invoices")
     */
    private $payments;

    /**
     * @var \DateTime
     * @ORM\Column(name="sent_to_supplier_at", type="datetime")
     */
    private $sentToSupplierAt;

    /**
     * @var string
     * @ORM\Column(name="status", type="string", length=20)
     */
    private $status;

    public function __construct()
    {
        $this->status = self::STATUS_PENDING;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set xeroId
     *
     * @param string $xeroId
     *
     * @return Invoice
     */
    public function setXeroId($xeroId)
    {
        $this->xeroId = $xeroId;

        return $this;
    }

    /**
     * Get xeroId
     *
     * @return string
     */
    public function getXeroId()
    {
        return $this->xeroId;
    }

    /**
     * @return SupplierInvoice
     */
    public function getSupplierInvoice()
    {
        return $this->supplierInvoice;
    }

    /**
     * @param SupplierInvoice $supplierInvoice
     */
    public function setSupplierInvoice(SupplierInvoice $supplierInvoice)
    {
        $this->supplierInvoice = $supplierInvoice;
    }

    /**
     * @return float
     */
    public function getCommissionRate()
    {
        return $this->commissionRate;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function setCommissionRate()
    {
        $this->commissionRate = $this->findCommissionRate();
    }

    /**
     * @return float
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function setCommission()
    {
        $this->commission = $this->commissionRate * $this->supplierInvoice->getTotal();
    }

    /**
     * @return string
     */
    public function getTierLevel()
    {
        return $this->tierLevel;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function setTierLevel()
    {
        $this->tierLevel = $this->findTierLevel();
    }

    /**
     * @return \DateTime
     */
    public function getNextInvoiceIssueAt()
    {
        return $this->nextInvoiceIssueAt;
    }

    /**
     * @param \DateTime $nextInvoiceIssueAt
     */
    public function setNextInvoiceIssueAt($nextInvoiceIssueAt)
    {
        $this->nextInvoiceIssueAt = $nextInvoiceIssueAt;
    }

    public function getPaymentDueDate()
    {
       return $this->supplierInvoice->getPaymentDueDate();
    }

    public function getCommissionModels()
    {
        return $this->supplierInvoice->getCommissionTiers();
    }

    public function findCommissionRate()
    {
        return $this->supplierInvoice->findCommissionRate();
    }

    public function findTierLevel()
    {
        return $this->supplierInvoice->findTierLevel();
    }

    /**
     * @return Payment[] | ArrayCollection
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * @param Payment[] $payments
     */
    public function setPayments($payments)
    {
        $this->payments = $payments;
    }

   public function getSupplier()
   {
       return $this->supplierInvoice->getLeadSupplier()->getSupplier();
   }

    public function getLead()
    {
        return $this->supplierInvoice->getLeadSupplier()->getLead();
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return \DateTime
     */
    public function getDueAt()
    {
        return $this->dueAt;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function setDueAt()
    {
        $this->dueAt = $this->supplierInvoice->getPaymentDueDate();
    }

    /**
     * @return \DateTime
     */
    public function getSentToSupplierAt()
    {
        return $this->sentToSupplierAt;
    }

    /**
     * @param \DateTime $sentToSupplierAt
     */
    public function setSentToSupplierAt($sentToSupplierAt)
    {
        $this->sentToSupplierAt = $sentToSupplierAt;
    }

}

src/AppBundle/Form/InvoiceType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Lead;
use AppBundle\Entity\Invoice;
use AppBundle\Entity\LeadSupplier;
use AppBundle\Entity\Supplier;
use AppBundle\Entity\SupplierInvoice;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('supplierInvoice', EntityType::class, [
                'class' => SupplierInvoice::class,
                'choice_label' => function(SupplierInvoice $supplierInvoice) {
                    return "{$supplierInvoice->getReferenceNumber()} ( {$supplierInvoice->getLeadSupplier()->getSupplier()} )";
                },
                'query_builder' => function(EntityRepository $er) {
                    $qb = $er->createQueryBuilder('si');
                    $qb->leftJoin('si.invoice', 'i')
                        ->where($qb->expr()->isNull('i.id'))
                        ->orderBy('si.referenceNumber', 'ASC');
                    return $qb;
                },
                'placeholder' => 'Please Select Supplier Invoice',
                'attr' => [
                    'class' => 'supplier-invoice'
                ]
            ])
            ->add('xeroId', TextType::class, [
                    'label' => 'XERO ID'
            ])
            ->add('sentToSupplierAt', DateTimeType::class, [
                'date_widget' => 'single_text',
                'time_widget' => 'single_text',
                'format' => 'YYYY-MM-dd HH:mm',
                'input' => 'datetime',
                'view_timezone' => 'Australia/Melbourne',
                'label' => 'Date/time invoice sent to customer in XERO'
            ])
            ->add('nextInvoiceIssueAt', DateType::class, [
                'label' => 'Expected date next invoice copy should be received from Supplier',
                'widget' => 'single_text'
            ]);


    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Invoice'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_invoice';
    }


}

src/AppBundle/Controller/InvoiceController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Invoice;
use AppBundle\Form\InvoiceType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class InvoiceController
 *
 * @package AppBundle\Controller
 * @Route("/invoices")
 */
class InvoiceController extends Controller
{
    /**
     * @Route("/create", name="invoice_create")
     * @param Request $request
     *
     * @return Response
     */
    public function createAction(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($invoice);
            $manager->flush();
            $this->addFlash('success', 'Invoice Created');
            return $this->redirectToRoute('invoice_all');
        }

        return $this->render('AppBundle:Invoice:create.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("", name="invoice_all")
     */
    public function allAction()
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $manager = $this->getDoctrine()->getManager();

        $invoices = $manager->getRepository('AppBundle:Invoice')->findBy([], ['createdAt' => 'desc']);

        return $this->render('AppBundle:Invoice:all.html.twig', compact('invoices'));
    }

    /**
     * @Route("/{id}/view", name="invoice_view")
     *
     * @param $id
     * @param id
     *
     * @return Response
     */
    public function viewAction($id)
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $manager = $this->getDoctrine()->getManager();

        $invoice = $manager->find('AppBundle:Invoice', $id);

        return $this->render('AppBundle:Invoice:edit.html.twig', array(
            'invoice' => $invoice
        ));
    }

    /**
     * @Route("/{id}/edit", name="invoice_edit")
     *
     * @param $request
     * @param $id
     *
     * @return Response
     */
    public function editAction(Request $request, $id)
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $manager = $this->getDoctrine()->getManager();

        $invoice = $manager->find('AppBundle:Invoice', $id);

        $form = $this->createForm(InvoiceType::class, $invoice);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($invoice);
            $manager->flush();
            $this->addFlash('success', 'Invoice Updated');
            return $this->redirectToRoute('invoice_all');
        }

        return $this->render('AppBundle:Invoice:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/data", name="invoice_data")
     * @Method({"POST"})
     * @param $request
     *
     * @return string
     */
    public function invoiceDataAction(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');
        $manager = $this->getDoctrine()->getManager();

        if ($request->getMethod() == 'POST')
        {
            $ids = $request->get('ids');
            $invoices = $manager->getRepository('AppBundle:Invoice')->findBy(['id' => $ids]);
        }

        return new Response($this->renderView('@App/Invoice/data.html.twig',
            compact('invoices')));
    }

}

src/AppBundle/Resources/views/Invoice/all.html.twig
{% extends "ThemeBundle:layout:base-layout.html.twig" %}

{% block page_title %}Invoices{% endblock %}
{% block page_subtitle %}<a href="{{ url('invoice_create') }}" class="btn btn-success btn-md">Create Invoice</a>{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-success">
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Created At</th>
                            <th>Xero ID</th>
                            <th>Supplier</th>
                            <th>Lead</th>
                            <th>Service</th>
                            <th>Function</th>
                            <th>Amount of Customer Invoice ($)</th>
                            <th>Tier Level</th>
                            <th>Commission Rate</th>
                            <th>Commissions ($)</th>
                            <th>CX Connect invoice due date</th>
                            <th>Next invoice due to be issued on</th>
                            <th>Status</th>
                            <th data-sortable="false"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for invoice in invoices %}
                            <tr>
                                <td>{{ invoice.createdAt|date }}</td>
                                <td>{{ invoice.xeroId }}</td>
                                <td>{{ invoice.supplier}}</td>
                                <td>{{ invoice.lead}}</td>
                                <td>{{ invoice.lead.service }}</td>
                                <td>
                                    {% for function in invoice.lead.function %}
                                        <p>{{ function }}</p>
                                    {% endfor %}
                                </td>
                                <td>{{ invoice.supplierInvoice.total| localizedcurrency('AUD') }}</td>
                                <td>{{ invoice.tierLevel}}</td>
                                <td>{{ (invoice.commissionRate * 100)| number_format(2)}}%</td>
                                <td>{{ (invoice.commission) | localizedcurrency('AUD') }}</td>
                                <td>{{ invoice.dueAt| date }}</td>
                                <td>{{ invoice.nextInvoiceIssueAt|date }}</td>
                                <td>{{ invoice.status }}</td>
                                <td><a class="btn bg-purple btn-xs" href="{{ path('invoice_edit', {'id' : invoice.id}) }}"><i class="fa fa-edit"></i></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Invoice/create.html.twig
{% extends "ThemeBundle:layout:base-layout.html.twig" %}

{% block page_title %}Create Invoice{% endblock %}
{% block page_subtitle %}{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-sm-5">
            {{ form_start(form) }}
            <!-- form start -->
            <div class="box box-success">
                <!-- /.box-header -->
                <div class="box-body">
                    {{ form_widget(form) }}
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary pull-right">Create</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
        <div class="col-sm-7">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Invoice Data</h3>
                    <!-- /.box-tools -->
                </div>
                <!-- /.box-header -->
                <div class="box-body invoice-data">
                </div>
            </div>

        </div>
    </div>
{% endblock %}
{% block javascripts_inline %}
    {{ parent() }}
    <script type="text/javascript">
        $('.supplier-invoice').change(function () {
            var supplierInvoiceId = $(this).val();
            var invoiceData = $('.invoice-data');
            if (supplierInvoiceId) {
                $.get('/supplier-invoices/' + supplierInvoiceId + '/invoice-data', function (data) {
                    invoiceData.html(data);
                });
            } else {
                invoiceData.html('<p>No invoice data available. Please select a supplier invoice first</p>');
            }
        }).change();
    </script>
{% endblock %}

src/AppBundle/Resources/views/Invoice/data.html.twig
{% for invoice in invoices %}
    <div class="panel panel-default">
        <div class="panel-heading">Invoice (XERO ID: {{ invoice.xeroId }}) </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-4"><strong>Created At</strong></div>
                <div class="col-sm-8"><p>{{ invoice.createdAt|date }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Supplier</strong></div>
                <div class="col-sm-8"><p>{{ invoice.supplier }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Lead</strong></div>
                <div class="col-sm-8"><p>{{ invoice.lead }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Amount of Customer Invoice ($)</strong></div>
                <div class="col-sm-8"><p>{{ invoice.supplierInvoice.total| localizedcurrency('AUD') }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Tier Level</strong></div>
                <div class="col-sm-8"><p>{{ invoice.tierLevel }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Commission Rate</strong></div>
                <div class="col-sm-8"><p>{{ (invoice.commissionRate * 100)| number_format(2)}}%</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Commissions ($)</strong></div>
                <div class="col-sm-8"><p>{{ (invoice.commission) | localizedcurrency('AUD') }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>CX Connect invoice due date</strong></div>
                <div class="col-sm-8"><p>{{ invoice.dueAt| date }}</p></div>
            </div>
            <div class="row">
                <div class="col-sm-4"><strong>Next invoice due to be issued on</strong></div>
                <div class="col-sm-8"><p>{{ invoice.nextInvoiceIssueAt|date }}</p></div>
            </div>
        </div>
    </div>

{% endfor %}

src/AppBundle/Resources/views/Invoice/edit.html.twig
{% extends "ThemeBundle:layout:base-layout.html.twig" %}

{% block page_title %}Edit Invoice{% endblock %}
{% block page_subtitle %}{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-sm-6">
            {{ form_start(form) }}
            <!-- form start -->
            <div class="box box-primary">
                <!-- /.box-header -->
                <div class="box-body">
                    {{ form_widget(form) }}
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary pull-right">Update</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}